model:
  # Backbone
  backbone_name: "sentence-transformers/nli-bert-base"
  freeze_repr: true

  # Encoder
  d_latent: 768
  d_model: 768
  n_latent_tokens: 2
  max_length: 16

  encoder_layers: 6
  encoder_heads: 12
  encoder_ff_dim: 3072
  encoder_dropout: 0.1

  # Decoder
  decoder_layers: 6
  decoder_heads: 12
  decoder_ff_dim: 3072
  decoder_dropout: 0.1

  # Latent augmentation
  noise_std: 0.2
  feature_dropout_p: 0.0

  # Loss
  lambda_sem: 0.2
