model:
  backbone_name: "sentence-transformers/all-mpnet-base-v2"
  freeze_repr: true
  
  n_latent_tokens: 8
  d_model: 768
  max_length: 16
  noise_std: 0.2
  sigma_type: "abs"
  feature_dropout_p: 0.0
  lambda_sem: 10
  normalize_latent: False

  # encoder
  encoder_layers: 6
  encoder_heads: 12
  encoder_ff_dim: 3072
  encoder_dropout: 0.1
  
  # decoder
  decoder_type: "autoregressive"
  decoder_layers: 6
  decoder_heads: 12
  decoder_ff_dim: 3072
  decoder_dropout: 0.1

train:
  output_dir: outputs/comp/nl_8_std_0.2_sl_10_try_2
  init_from_checkpoint: outputs/comp/nl_8_std_0.2_sl_10/checkpoint-416000/model.safetensors
  lr: 1.0e-4
  weight_decay: 0.01
  ema_decay: 0.999
  epochs: 100
  warmup_steps: 1000
  batch_size: 32
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  logging_steps: 100
  eval_steps: 1000
  save_steps: 1000
  save_total_limit: 2
  metric_for_best_model: eval/loss
  fp16: false
  bf16: false
  dataloader_num_workers: 16
  seed: 42
  report_to: tensorboard

data:
  preprocessed_dir: /home/okashurin/okashurin/datasets/fineweb_10bt_chunks
  num_train_samples: null
  num_val_samples: null
  seed: 42
