train:
  output_dir: outputs/vavae_mpnet_nl_2_std_0.2
  lr: 1.0e-4
  weight_decay: 0.01
  epochs: 100
  warmup_steps: 1000
  batch_size: 32
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  logging_steps: 100
  eval_steps: 1000
  save_steps: 1000
  save_total_limit: 2
  fp16: false
  bf16: false
  dataloader_num_workers: 16
  seed: 42
  report_to: tensorboard
  ema_decay: 0.999