train:
  output_dir: outputs/bottleneck_no_repr_test
  lr: 1.0e-4
  weight_decay: 0.01
  epochs: 100
  warmup_steps: 1000
  batch_size: 64
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  logging_steps: 5
  eval_steps: 50
  save_steps: 50
  save_total_limit: 3
  fp16: false
  bf16: false
  dataloader_num_workers: 16
  seed: 42
  report_to: tensorboard
