model:
  ae_config_path: "/home/okashurin/okashurin/TSAE/outputs/comp/nl_8_std_0.2_sl_10/config.yaml"
  ae_checkpoint_path: /home/okashurin/okashurin/TSAE/outputs/comp/nl_8_std_0.2_sl_10/checkpoint-416000/model.safetensors
  pretrained_gpt2: "openai-community/gpt2"
  max_model_seq_len: null
  lambda_mse: 0.0
  lambda_answer_ce: 1.0

train:
  output_dir: "outputs/hybrid_latent/nl_1_sl_0"
  init_from_checkpoint: /home/okashurin/okashurin/TSAE/outputs/hybrid_latent/test/checkpoint-60100/model.safetensors
  lr: 1.0e-5
  weight_decay: 0.001
  ema_decay: 0.9999
  epochs: 100
  warmup_steps: 100
  batch_size: 64
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  logging_steps: 20
  eval_steps: 200
  save_steps: 200
  save_total_limit: 2
  fp16: false
  bf16: true
  dataloader_num_workers: 16
  seed: 42
  report_to: tensorboard
  metric_for_best_model: null

data:
  dataset_name: "booydar/gsm8k"
  dataset_config: "default"
  task_column: "task"
  cot_column: "cot"
  labels_column: "labels"
  cache_dir: null
  reasoning_trigger: "!!!!"
  end_of_thinking_phrase: "end of thinking"
  gpt2_tokenizer_name: "openai-community/gpt2"
  max_prompt_tokens: 100
  max_answer_tokens: 8
  max_cot_steps: 10
  num_train_samples: null
  num_val_samples: 10000
  seed: 42
